ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(160);

ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt_email VARCHAR(160);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt_phone VARCHAR(60);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt_url TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS receipt_status VARCHAR(20) NOT NULL DEFAULT 'none';
