-- 28 новых профессий для шабашки. Сварщик и плиточник уже есть — не дублируем.
INSERT INTO t_p87694549_free_task_finder.professions (slug, label, icon) VALUES
('mason','Каменщик','BrickWall'),
('plasterer','Штукатур','Layers'),
('wallpaper','Обойщик','Wallpaper'),
('flooring','Укладка полов','SquareStack'),
('drywall','Гипсокартон','PanelTop'),
('doors','Установка дверей','DoorOpen'),
('windows','Установка окон','Frame'),
('ceilings','Натяжные потолки','Blinds'),
('heating','Отопление и котлы','Thermometer'),
('aircon','Кондиционеры','Wind'),
('ventilation','Вентиляция','AirVent'),
('wells','Скважины и колодцы','Waves'),
('lowvoltage','Интернет и видеонаблюдение','Router'),
('fencing','Заборы и ограждения','Fence'),
('bathhouse','Бани и беседки','Building2'),
('paving','Тротуарная плитка','Blocks'),
('treecut','Спил деревьев','TreePine'),
('tractor','Тракторные работы','Tractor'),
('cargo','Газель, грузоперевозки','Truck'),
('wasteremoval','Вывоз мусора','Trash2'),
('automaster','Автомастер','Car'),
('appliancerepair','Ремонт бытовой техники','WashingMachine'),
('computerhelp','Компьютерная помощь','MonitorSmartphone'),
('drycleaning','Химчистка мебели','Sofa'),
('windowwash','Мытьё окон','PanelTop'),
('pestcontrol','Дезинсекция','SprayCan'),
('household','Помощь по хозяйству','HeartHandshake'),
('petcare','Присмотр за животными','PawPrint')
ON CONFLICT (slug) DO NOTHING;